### ISSUE TITLE
Support for multiple

### ISSUE THREAD

**Issue by NeoPrimate** [PabloRuizCuevas/numty#2]
I'd like to be able to multiply a matrix with a vector using Numty.

Supporting this in the matmul function would be useful:

```
#import "@preview/numty:0.0.4" as nt

#let A = (
  (-1, 1),
  (2, 0),
)

#let x0 = (-2, -2)

#nt.matmult(A, x0)
```

On discord SillyFreak, suggested these as an alternative:

```
#let matvecmul(A, x) = {
  let X = x.map(x => (x,))
  let Y = nt.matmul(A, X)
  let y = Y.map(array.first)
  y
}
#let vecmatmul(x, A) = {
  let X = (x,)
  let Y = nt.matmul(X, A)
  let y = Y.first()
  y
}

#matvecmul(A, x0)
#vecmatmul(x0, A)
```

Thanks for this very cool library <3

**Comment by PabloRuizCuevas** [comment]
hi! Well is actually somewhat supported already:

You can do: 
 #nt.matmul( ((1,3))                ,   ((16,23),(13,19)))
 #nt.matmul( ((16,23),(13,19)),   ((1,), (3,)) )

The results of these operations are the same but transposed. you can use nt.transpose and then take the first element with .at(0)  if you really don't want your vectors being nested lists.

I know the col vector syntax in typst is awful:  ((1,), (3,))  and in principle the plan is that you do nt.transpose((1,3)), but transposition of vectors is not yet supported, probably in the next version.  Maybe I make nt.col(1,3, ...)  to define columns, still undecided.

Said that I'm a bit hesitant to introduce  matvecmul and vecmatmul functions as one of the main features of this library is broadcasting rather than forcing specific user input.

But suggestions are always welcomed!

**Comment by PabloRuizCuevas** [comment]
you are welcomed!  

Is not supported yet as you may have seen, but will be the main priority.

**Comment by SillyFreak** [comment]
Thinking about it a bit more, these functions (like `matmul` too) could handle more than two parameters:
- `matmul(..matrices)` would multiply all its matrices
- `matvecmul(..matrices, vec)` and `vecmatmul(vec, ..matrices)` would convert the last/first parameter to a matrix and the result back to a vector

It could also be useful to provide standalone functions to convert between 1D-arrays (row and col vectors) and matrices.

sorry, I hope I'm not exploding the scope of this issue :P

**Comment by PabloRuizCuevas** [comment]
I have the hope that typst will have classes in the future and these functions are converted to dunder methods -> operators , if that happens matmul will be  A @ B  same as in numpy... that probably takes a geological time span so back down to earth, there is a super convenient way of doing this: (A,B,C).reduce(nt.matmul) so the added value of chanting all the code and introducing one more iteration is small that would need to be there in so many places (for consistency).

Your second suggestion is great, and will be part of the next release, I called it nt.c and nt.r (though i proably import them directly as c and r) they use spreading for convenience.

**Comment by PabloRuizCuevas** [comment]
I close this issue, in the last version the recommended way is either defining col, row vectors or using the new utility functions r,c :

#import "@preview/numty:0.0.4" as nt
#nt.matmult(A, nt.c(..x0))

Or like this:

#import "@preview/numty:0.0.4" : c
#nt.matmult(A, c(..x0))
